# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: CYBERSTALKER07
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tashkent

          # Omni Theme
          extras_css: |
            /* === Omni Theme === */
            svg { color: #7C71A6; }
            h1, h2, h3 { color: #78D1E1; }
            .field svg { fill: #7C71A6; }
            .error { color: #E96379; }
            .error svg { fill: #E96379; }
            .warning { color: #E7DE79; }
            .warning svg { fill: #E7DE79; }
            .contrib-s { color: #E96379; background-color: #E9637926; border-color: #E96379; }
            .contrib-a { color: #E7DE79; background-color: #E7DE7926; border-color: #E7DE79; }
            .contrib-b { color: #988BC7; background-color: #988BC726; border-color: #988BC7; }
            .contrib-c { color: #78D1E1; background-color: #78D1E126; border-color: #78D1E1; }
            .label { background-color: #78D1E130; color: #78D1E1; }
            .gauge.high .color { color: #67E480; }
            .gauge.average .color { color: #E89E64; }
            .gauge.low .color { color: #E96379; }
            .gauge.high svg { fill: #67E480; }
            .gauge.average svg { fill: #E89E64; }
            .gauge.low svg { fill: #E96379; }
            .audit-high { fill: #67E480; }
            .audit-average { fill: #E89E64; }
            .audit-low { fill: #E96379; }
            .field .value { color: #7C71A6; }
            .achievement .title { color: #78D1E1; }
            .footnote, .minor, .minify { color: #614F8A; }
            a { color: #78D1E1; }
            .progress-bar .done { background-color: #67E480; }
            .progress-bar .doing { background-color: #988BC7; }
            .progress-bar .todo { background-color: #483C67; }

          # Plugins
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_stars: yes
          plugin_stars_limit: 4
          
